#pragma once

#define BOARD_USB_NUM 2


/*

#define BOARD_HAS_LED
#define BOARD_PIN_LED

#define BOARD_HAS_FINGERPRINT_MODULE
#define BOARD_FINGERPRINT_PIN_EN
#define BOARD_FINGERPRINT_PIN_TX
#define BOARD_FINGERPRINT_PIN_RX
#define BOARD_FINGERPRINT_PIN_IRQ

#define BOARD_HAS_BATTARY
#define BOARD_PIN_BATTARY
#define BOARD_BATTARY_VOLTAGE_SCALE

#define BOARD_USB1_PIN_DP
#define BOARD_USB1_PIN_DM
#define BOARD_USB2_PIN_DP
#define BOARD_USB2_PIN_DM
*/